version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"   # NameNode Web UI
      - "8020:8020"   # NameNode RPC port
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
      - HDFS_CONF_dfs_replication=1
    volumes:
      - namenode_data:/hadoop/dfs/name
    networks:
      - hadoop_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 10s
      retries: 5

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      namenode:
        condition: service_healthy
    ports:
      - "9864:9864"   # DataNode Web UI
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    volumes:
      - datanode_data:/hadoop/dfs/data
    networks:
      - hadoop_net

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_started
    ports:
      - "8088:8088"   # ResourceManager Web UI
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
    networks:
      - hadoop_net

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    depends_on:
      resourcemanager:
        condition: service_started
    ports:
      - "8042:8042"   # NodeManager Web UI
    networks:
      - hadoop_net

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_started
      resourcemanager:
        condition: service_started
    ports:
      - "8188:8188"   # HistoryServer Web UI
    networks:
      - hadoop_net

volumes:
  namenode_data:
  datanode_data:

networks:
  hadoop_net:
    driver: bridge
